// Utilities
import { defineStore } from "pinia";

export const useFacultyMembersStore = defineStore("FacultyMembers", {
  state: () => ({
    FacultyMembers: [
      {
        id: "1",
        firstName: "رضوان",
        fatherName: "علي",
        lastName: "حسين",
        email: "radwan@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقينة المعلومات",
        department: "قسم هندسة البرمجيات",
        qualification: "دكتوراه",
        currentDegree: "أستاذ مشارك",
        dateOfObtaining: null,
      },
      {
        id: "2",
        firstName: "الحرمين",
        fatherName: "محمد",
        lastName: "الحرمين",
        email: "haramin@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقنية المعلومات",
        department: "قسم هندسة البرمجيات",
        qualification: "دكتوراه",
        currentDegree: "أستاذ",
        dateOfObtaining: null,
      },
      {
        id: "3",
        firstName: "عبدالحميد",
        fatherName: "",
        lastName: "الواعر",
        email: "alwaer@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقنية المعلومات",
        department: "قسم هندسة البرمجيات",
        qualification: "دكتوراه",
        currentDegree: "أستاذ مساعد",
        dateOfObtaining: null,
      },
      {
        id: "4",
        firstName: "مروة",
        fatherName: "نوري",
        lastName: "صولة",
        email: "solla@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقنية المعلومات",
        department: "قسم هندسة البرمجيات",
        qualification: "ماجستير",
        currentDegree: "أستاذ مساعد",
        dateOfObtaining: null,
      },
      {
        id: "5",
        firstName: "حنان",
        fatherName: "",
        lastName: "الداقيز",
        email: "hanan@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقنية المعلومات",
        department: "قسم نظم المعلومات",
        qualification: "دكتوراه",
        currentDegree: "أستاذ",
        dateOfObtaining: null,
      },
      {
        id: "6",
        firstName: "ادريس",
        fatherName: "",
        lastName: "غميض",
        email: "edris@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية تقنية المعلومات",
        department: "قسم الشبكات",
        qualification: "دكتوراه",
        currentDegree: "أستاذ مشارك",
        dateOfObtaining: null,
      },
      {
        id: "7",
        firstName: "جمال",
        fatherName: "",
        lastName: "اندير",
        email: "jamal@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية العلوم",
        department: "قسم الإحصاء",
        qualification: "دكتوراه",
        currentDegree: "أستاذ مشارك",
        dateOfObtaining: null,
      },
      {
        id: "8",
        firstName: "السايح",
        fatherName: "",
        lastName: "الهباشي",
        email: "alsayeh@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية الهندسة",
        department: "قسم الهندسية الكهربائية والإلكترونية",
        qualification: "دكتوراه",
        currentDegree: "أستاذ",
        dateOfObtaining: null,
      },
      {
        id: "9",
        firstName: "مختار",
        fatherName: "",
        lastName: "العالم",
        email: "mokhtar@uot.edu.ly",
        nationality: "ليبي",
        faculty: "كلية الزراعة",
        department: "قسم التربة والمياه",
        qualification: "دكتوراه",
        currentDegree: "أستاذ",
        dateOfObtaining: null,
      },
    ],
  }),
  actions: {
    crudChange(newFData) {
      console.log(this.FacultyMembers);
      this.FacultyMembers = newFData;
      console.log(this.FacultyMembers);
    },
  },
});
